### ISSUE TITLE
Bundlerがインストールされていない環境で実行できない

### ISSUE THREAD

**Issue by kenchan** [moro/spe_cuke#2]
gemspecではdevelopment_dependencyになっていますが、lib/environment.rbでrequireされています。

Bundlerをrequireするのではなく、他の方法でBundlerが使われているかどうか判断するようにしていただけませんか。

**Comment by moro** [comment]
ものすごく安易に直してみたがどうか。

https://github.com/moro/spe_cuke/commit/c5e0da8a7085e8ae2b314c25b6a0c4a67098ce64

**Comment by kenchan** [comment]
ありがとうございます。いいと思います。

**Comment by kenchan** [comment]
4年越しのclose
